In [0]:
import numpy as np


In [2]:
np.array([14,212,21])

array([ 14, 212,  21])

Mencionar como importar biblioteca y el manejo de esta como objetos


In [3]:
a = np.array([10,20,30])
a[2]

30

In [0]:
a[1:] #alternativa a ciclo for 


array([20, 30])

In [0]:
#Forma de llenar arreglos 
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [5]:
#Bidimensional sin ceros
np.ones((4,5))


array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [4]:
# Inicio , Fin , Intervalo
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [0]:
#Crear arreglo bidimensional
b = np.array([['x','y'],['a','b']]) 
print(b)
type(b)

[['x' 'y']
 ['a' 'b']]


numpy.ndarray

In [0]:
c = [12,40,2,10,4]
np.sort(c)

array([ 2,  4, 10, 12, 40])

In [0]:
header = [ ('nombre','S10'), ('edad',int)] #nombre -> estring de 10 elemntos , edad -> tipo entero
datos = [('Alfonso',10),('Mario',70),('Eduardo',21),('Richie',15)]
usuarios = np.array(datos,dtype = header)

#Para ordenar
np.sort(usuarios,order= 'edad') #Indicamos que datos mandaremos y como lo queremos ordenar
#np.sort(usuarios,order= 'nombre')


array([(b'Alfonso', 10), (b'Richie', 15), (b'Eduardo', 21),
       (b'Mario', 70)], dtype=[('nombre', 'S10'), ('edad', '<i8')])

In [0]:
#LLenado de arreglos o vectores unidimensionales
np.arange(25) 
np.arange(10,20) # rango
np.arange(10,20,2) # rango y cada cuanto

array([10, 12, 14, 16, 18])

In [0]:
#Diagonal de la matriz
np.diag([0,3,6,9])

array([[0, 0, 0, 0],
       [0, 3, 0, 0],
       [0, 0, 6, 0],
       [0, 0, 0, 9]])