In [1]:
import tensorflow as tf

nodo1 = tf.constant(3.0,dtype=tf.float32)
nodo2 = tf.constant(2.112)

print(nodo1)
print(nodo2)

vector = tf.constant([1,45,78]) #Metodo del objeto tf -> es para constantes
print(vector)

Tensor("Const:0", shape=(), dtype=float32)
Tensor("Const_1:0", shape=(), dtype=float32)
Tensor("Const_2:0", shape=(3,), dtype=int32)


In [0]:
###Ejemplos de sintaxis
import tensorflow as tf

#escalares
entero = tf.Variable(5,tf.int32)
real = tf.Variable(3.71232, tf.float32) 

#Vectores
IntVector = tf.Variable([1,2,3,4],tf.int16)
floatVector = tf.Variable([4.344,5.31],tf.float32)

#Matrices
matrixfloat = tf.Variable([[1.1,2.2],[3.3,4.4]],tf.float32)
matrixStrings = tf.Variable([["Hola","a "],["todos",":D"]],tf.string)
#print(matrixStrings)

In [0]:
"""
En matemáticas, un tensor es un objeto algebraico 
que describe un mapeo lineal de un conjunto de objetos algebraicos a otro
Cálculo Tensorial
"""

In [6]:
import tensorflow as tf

IntVector = tf.constant([1,2,3,4])
MatrixVector = tf.constant([[1,2,3,4],[1,2,3,4]])

#Sesiones -> Ha cambiado en la versión 2.X 
with tf.Session() as s:
  print(s.run(IntVector))
  print('\n')
  print(s.run(MatrixVector))

[1 2 3 4]


[[1 2 3 4]
 [1 2 3 4]]
